spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: XXX
            clientSecret: XXX
          facebook:
            clientId: XXX
            clientSecret: XXX
#logging:
#  level:
#    org.springframework.security: DEBUG
